# Dependencies
plugins: [jekyll-paginate]

# Features
excerpt_separator: <!--more-->
categories: "quant|finance|maths|physics|crypto|programming|machine-learning"


# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Reasonable Deviations
tagline:          'a rational approach to complexity'
description:      'a rational approach to complexity'
url:               'https://reasonabledeviations.com'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Robert Andrew Martin'
  email:        'martin.robertandrew@gmail.com'


# Custom vars
future: TRUE
version:          2.1.0

github:
  repo:           https://github.com/robertmartin8

social:
    linkedin: https://www.linkedin.com/in/robert-a-martin/
    twitter: https://twitter.com/robertmartin88

# Structure
paginate:         10

collections:
  notes:
      output: true
      permalink: /notes/:path/
